/* SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2021, Silicon Labs
 * Copyright (c) 2019, Arm Limited and affiliates.
 * Main authors:
 *     - Jérôme Pouiller <jerome.pouiller@silabs.com>
 */
#ifndef WSBR_CERTS_H
#define WSBR_CERTS_H

static const uint8_t WISUN_ROOT_CERTIFICATE[] =
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICmDCCAj2gAwIBAgIJAPXEa83exaPFMAoGCCqGSM49BAMCMIGfMQswCQYDVQQG\r\n"
    "EwJGUjELMAkGA1UECAwCRlIxDzANBgNVBAcMBlJlbm5lczEcMBoGA1UECgwTU2ls\r\n"
    "aWNvbiBMYWJzIEZyYW5jZTEMMAoGA1UECwwDUiZEMRowGAYDVQQDDBFXaS1TVU4g\r\n"
    "VGVzdGluZyBDQTEqMCgGCSqGSIb3DQEJARYbdHVvbWFzLm1hYXR0YW5lbkBzaWxh\r\n"
    "YnMuY29tMB4XDTIwMDExNDE0NDEwNloXDTI1MDExMjE0NDEwNlowgZ8xCzAJBgNV\r\n"
    "BAYTAkZSMQswCQYDVQQIDAJGUjEPMA0GA1UEBwwGUmVubmVzMRwwGgYDVQQKDBNT\r\n"
    "aWxpY29uIExhYnMgRnJhbmNlMQwwCgYDVQQLDANSJkQxGjAYBgNVBAMMEVdpLVNV\r\n"
    "TiBUZXN0aW5nIENBMSowKAYJKoZIhvcNAQkBFht0dW9tYXMubWFhdHRhbmVuQHNp\r\n"
    "bGFicy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQKqkm1zos92BwD6jxa\r\n"
    "g82zozNwbTw6Y1d9APcH6RCWzaoTYXu13zewktPYPU4AocrkK2jJdt7cxipbxiSx\r\n"
    "dRQro2AwXjAPBgNVHRMBAf8EBTADAQH/MAsGA1UdDwQEAwIBBjAdBgNVHQ4EFgQU\r\n"
    "quZSRE1EjJDyqY10hUWsHWjwAtEwHwYDVR0jBBgwFoAUquZSRE1EjJDyqY10hUWs\r\n"
    "HWjwAtEwCgYIKoZIzj0EAwIDSQAwRgIhALkJ+4FYq+1vdobQrQI5LrCkkNPe/NeS\r\n"
    "v7vDalV6UHqSAiEA8ncGWs1haoL/UomMo5bXtS+ov8wV6ibwp5vMkf0ckio=\r\n"
    "-----END CERTIFICATE-----";

static const uint8_t WISUN_SERVER_CERTIFICATE[] =
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIClDCCAjugAwIBAgIJAND+U5bQNkNiMAoGCCqGSM49BAMCMIGfMQswCQYDVQQG\r\n"
    "EwJGUjELMAkGA1UECAwCRlIxDzANBgNVBAcMBlJlbm5lczEcMBoGA1UECgwTU2ls\r\n"
    "aWNvbiBMYWJzIEZyYW5jZTEMMAoGA1UECwwDUiZEMRowGAYDVQQDDBFXaS1TVU4g\r\n"
    "VGVzdGluZyBDQTEqMCgGCSqGSIb3DQEJARYbdHVvbWFzLm1hYXR0YW5lbkBzaWxh\r\n"
    "YnMuY29tMB4XDTIwMDExNTE2MzMzNFoXDTI1MDExMzE2MzMzNFowgaMxCzAJBgNV\r\n"
    "BAYTAkZSMQswCQYDVQQIDAJGUjEPMA0GA1UEBwwGUmVubmVzMRwwGgYDVQQKDBNT\r\n"
    "aWxpY29uIExhYnMgRnJhbmNlMQwwCgYDVQQLDANSJkQxHjAcBgNVBAMMFVdpLVNV\r\n"
    "TiBUZXN0aW5nIFNlcnZlcjEqMCgGCSqGSIb3DQEJARYbdHVvbWFzLm1hYXR0YW5l\r\n"
    "bkBzaWxhYnMuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEH5DaEIN1AGBe\r\n"
    "Q4s1K5IBvHn4VPHVSKUliZbYg2QBCWlLfD8IL14zto05uYfN7ffH8M2fyM2BiaxN\r\n"
    "BoRonczc+KNaMFgwCQYDVR0TBAIwADALBgNVHQ8EBAMCBeAwHQYDVR0OBBYEFDTl\r\n"
    "6IbtAgU0ogpxJF9rBhbWnEC9MB8GA1UdIwQYMBaAFKrmUkRNRIyQ8qmNdIVFrB1o\r\n"
    "8ALRMAoGCCqGSM49BAMCA0cAMEQCIHKDn9kL5koqbcrW5gQrB//7YlgOm9iu5hju\r\n"
    "yU5ruOFMAiBoOwjBho3mBRFjInwW6/CmlZ/XwMSjkVzUcwpeR1dozA==\r\n"
    "-----END CERTIFICATE-----";

static const uint8_t WISUN_SERVER_KEY[] =
    "-----BEGIN EC PRIVATE KEY-----\r\n"
    "MHcCAQEEILRF7+wGLZ7ZVqEZBhovNC2ml5ZTzR7vpjRd3WnkBnXRoAoGCCqGSM49\r\n"
    "AwEHoUQDQgAEH5DaEIN1AGBeQ4s1K5IBvHn4VPHVSKUliZbYg2QBCWlLfD8IL14z\r\n"
    "to05uYfN7ffH8M2fyM2BiaxNBoRonczc+A==\r\n"
    "-----END EC PRIVATE KEY-----";

static const uint8_t WISUN_CLIENT_CERTIFICATE[] =
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIC2DCCAn+gAwIBAgIJAND+U5bQNkNkMAoGCCqGSM49BAMCMIGfMQswCQYDVQQG\r\n"
    "EwJGUjELMAkGA1UECAwCRlIxDzANBgNVBAcMBlJlbm5lczEcMBoGA1UECgwTU2ls\r\n"
    "aWNvbiBMYWJzIEZyYW5jZTEMMAoGA1UECwwDUiZEMRowGAYDVQQDDBFXaS1TVU4g\r\n"
    "VGVzdGluZyBDQTEqMCgGCSqGSIb3DQEJARYbdHVvbWFzLm1hYXR0YW5lbkBzaWxh\r\n"
    "YnMuY29tMB4XDTIwMDExNTE2NDA1M1oXDTI1MDExMzE2NDA1M1owgaMxCzAJBgNV\r\n"
    "BAYTAkZSMQswCQYDVQQIDAJGUjEPMA0GA1UEBwwGUmVubmVzMRwwGgYDVQQKDBNT\r\n"
    "aWxpY29uIExhYnMgRnJhbmNlMQwwCgYDVQQLDANSJkQxHjAcBgNVBAMMFVdpLVNV\r\n"
    "TiBUZXN0aW5nIENsaWVudDEqMCgGCSqGSIb3DQEJARYbdHVvbWFzLm1hYXR0YW5l\r\n"
    "bkBzaWxhYnMuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEREjG2cnUrYPI\r\n"
    "n9Ul8IwQnqX4BEw6hRnyVeVYtGayfDDVdeS6PTtiq9olKB85oe+KBhkoe1xKlLbb\r\n"
    "TgoExIuHJKOBnTCBmjAJBgNVHRMEAjAAMAsGA1UdDwQEAwIF4DAUBgNVHSUEDTAL\r\n"
    "BgkrBgEEAYLkJQEwKgYDVR0RBCMwIaAfBggrBgEFBQcIBKATMBEGBysGAQQBKgEE\r\n"
    "BjEyMzQ1NjAdBgNVHQ4EFgQU8n8OEP/4xp8MC5E8jaaYb7m4lgowHwYDVR0jBBgw\r\n"
    "FoAUquZSRE1EjJDyqY10hUWsHWjwAtEwCgYIKoZIzj0EAwIDRwAwRAIgdjycrfjF\r\n"
    "NYiMQxNCVYbENuPPuWHBmVwGqPnQpnB3jh8CIGWTCfd8l76D65vYDw3aFLmirzkF\r\n"
    "1n+HekwwaDePvN4V\r\n"
    "-----END CERTIFICATE-----";

static const uint8_t WISUN_CLIENT_KEY[] =
    "-----BEGIN EC PRIVATE KEY-----\r\n"
    "MHcCAQEEINEvBfH5Pg7PdpZXENMIAafWCp3a0cX3PGPQtNsQrBhuoAoGCCqGSM49\r\n"
    "AwEHoUQDQgAEREjG2cnUrYPIn9Ul8IwQnqX4BEw6hRnyVeVYtGayfDDVdeS6PTti\r\n"
    "q9olKB85oe+KBhkoe1xKlLbbTgoExIuHJA==\r\n"
    "-----END EC PRIVATE KEY-----";

#endif
