# Silicon Labs Wi-SUN Direct Connect configuration example

# See wsbrd.conf for documentation and details on the various configuration keys.
# Note only the keys mentioned in this file are supported by silabs-ws-dc.

###############################################################################
# RCP serial configuration
###############################################################################

uart_device = /dev/ttyACM0
#uart_baudrate = 115200
#uart_rtscts = false
#cpc_instance = cpcd_0

###############################################################################
# Linux administration
###############################################################################

user = wsbrd
group = wsbrd
#tun_device = tun0
#tun_autoconf = true

###############################################################################
# Direct Connect specific
###############################################################################

# EUI-64 of the device silabs-ws-dc must establish a Direct Connection with.
# This parameter is mutually exclusive with target_id.
target_eui64=ff:ff:ff:ff:ff:ff:ff:ff

# Pairwise Master Key (PMK) used to secure the Direct Connection.
# This PMK must be the same one that is provided to the target.
# Required when target_eui64 is set. Mutually exclusive with target_id.
target_pmk=00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00

# When set, silabs-ws-dc will send Direct Connect Identity Solicit (DCIS)
# frames containing this ID to discover Direct Connect targets.
# Available Direct Connect targets respond with Direct Connect Identity (DCI)
# frames. This parameter is mutually exclusive with target_eui64.
# The ID is a string of up to 32 characters. Empty string is not allowed.
# Escape sequences like \x20 are supported.
#target_id = my_target_id

# How often silabs-ws-dc must send a Direct Connect Solicit frame to the
# targeted device.
# When target_id is set, this represents how often silabs-ws-dc must send a
# DCIS frame.
#disc_period_s = 10

# Maximum number of Direct Connect Solicit frames silabs-ws-dc can send before
# considering the device unreachable and exit with an error message.
# When target_id is set, this limits the number of DCIS frames sent.
# 0 = no limit.
#disc_count_max = 6

###############################################################################
# Wi-SUN PHY and frequency hopping
###############################################################################

domain = NA
chan_plan_id = 1
phy_mode_id = 0x02
#tx_power = 14
#allowed_channels = 0-255
#unicast_dwell_interval = 255

###############################################################################
# Backwards compatibility
###############################################################################

#class =
#mode =
#chan0_freq =
#chan_spacing =
#chan_count =

###############################################################################
# Miscellaneous and debug
###############################################################################

#color_output = auto
rcp_trace = mac

# Traces supported by silabs-ws-dc are:
# - bus:        trace native UART raw bytes
# - cpc:        trace CPC bus
# - hif:        trace HIF packets with command/property IDs dissected
# - hif-extra:  trace HIF packets fully dissected with type annotations
# - tun:        trace packets going through the TUN device
# - 15.4:       trace all IEEE 802.15.4 frames
# - security:   trace security operations (authentication, GTK/LGTK management)
#               /!\ dumps cryptographic secrets to stdout /!\
# - ipv6:       trace IPv6 packets with source/destination
# - icmp:       trace ICMPv6 packets with type (NS)
# - drop:       trace any packet refused or partially ignored with reason
# - neigh-15.4: trace 15.4 neighbor cache management
trace = 15.4,icmp,drop
