# Wi-SUN authenticator configuration example

# See wsbrd.conf for documentation and details on the various configuration keys.
# Note only the keys mentioned in this file are supported by silabs-ws-auth.

###############################################################################
# Wi-SUN security
###############################################################################

# Authenticator EUI-64 used to derive pairwise keys during protocol hanshakes.
# Since silabs-ws-auth does not use a RCP, there is no default hardware
# location from which to read this value so it must be set.
#mac_address = ff:ff:ff:ff:ff:ff:ff:ff

# IP address to use for sending and receiving EAPoL Relay packets. The
# default binding to all interfaces (::) is suitable for most setup. If a wsbrd
# instance runs on the same host as silabs-ws-auth, both programs will try to
# bind a EAPoL Relay socket. In this case bind_address needs to be set to ::1
# or to an address assigned to the backhaul network interface.
#bind_address = ::

# MQTT broker used to distribute (L)GTKs to border routers. The broker is
# usually expected to run on the same host as silabs-ws-auth. To pass TLS
# identity verification, mqtt_broker needs to align with the broker certificate
# identity. Alternatively, a local UNIX socket may be used without TLS.
#mqtt_broker = localhost
#mqtt_authority =
#mqtt_certificate =
#mqtt_key =

key = examples/br_key.pem
certificate = examples/br_cert.pem
authority = examples/ca_cert.pem
#radius_server =
#radius_secret =
#pmk_lifetime = 172800 # 4 months
#lpmk_lifetime = 788400 # 18 months (LFN)
#ptk_lifetime = 86400 # 2 months
#lptk_lifetime = 525600 # 12 months (LFN)
#gtk_expire_offset = 43200 # 30 days
#lgtk_expire_offset = 129600 # 90 days
#gtk_new_activation_time = 720
#lgtk_new_activation_time = 180
#gtk_new_install_required = 80
#lgtk_new_install_required = 90
#ffn_revocation_lifetime_reduction = 30
#lfn_revocation_lifetime_reduction = 30

#enable_lfn = true
#enable_ffn10 = false

###############################################################################
# Miscellaneous and debug
###############################################################################

#storage_prefix = /var/lib/silabs-ws-auth/

# Enable some debug traces. Same semantic than the -T option of wsbrd. This
# parameter and -T are cumulative.
# - drop:       trace any packet refused or partially ignored with reason
# - security:   trace security operations (authentication, GTK/LGTK management)
#               /!\ dumps cryptographic secrets to stdout /!\
# - mbedtls:    trace mbedtls for debugging
# - mqtt:       trace libmosquitto MQTT events for external authenticator
trace = drop

#gtk[0] = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
#gtk[1] = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
#gtk[2] = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
#gtk[3] = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
#lgtk[0] = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
#lgtk[1] = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
#lgtk[2] = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
