# SPDX-License-Identifier: LicenseRef-MSLA
# SPDX-Copyright-Text: (c) 2024 Silicon Laboratories Inc. (www.silabs.com)
name: Build
on:
  push:
    branches: [main, master, staging, next]
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ github.repository_owner == 'SiliconLabsInternal' && 'silabs-internal' || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Necessary for git-describe used by version.sh
          fetch-depth: 0
          fetch-tags: true
      # Forks do not copy upstream tags by default
      - name: Update tags
        run: |
          git remote add upstream https://github.com/SiliconLabs/wisun-br-linux
          git fetch upstream refs/tags/*:refs/tags/*
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          [ ${{ github.repository_owner }} = SiliconLabsInternal ] && \
          sudo apt-get install -y build-essential cargo
          sudo apt-get install -y ninja-build \
                                  libnl-3-dev libnl-route-3-dev \
                                  libcap-dev libsystemd-dev \
                                  libmosquitto-dev \
                                  libdbus-1-dev
          cargo fetch --manifest-path=tools/wsbrd_cli/Cargo.toml
      - name: Install MbedTLS
        run: |
          git clone --branch v3.6.2 \
                    --depth 1 \
                    --recurse-submodules \
                    --shallow-submodules \
                    https://github.com/ARMmbed/mbedtls
          cmake -S mbedtls \
                -B mbedtls/build \
                -D ENABLE_PROGRAMS=OFF \
                -D ENABLE_TESTING=OFF \
                -G Ninja
          ninja -C mbedtls/build
          sudo ninja -C mbedtls/build install
      - name: Compile and install
        run: |
          cmake -S . \
                -B build \
                -D COMPILE_WSRD=ON \
                -D COMPILE_DEVTOOLS=ON \
                -D COMPILE_DEMOS=ON \
                -D CMAKE_C_FLAGS=-Werror \
                -G Ninja
          ninja -C build
          sudo ninja -C build install
      - name: Run --version
        run: wsbrd --version
      - name: Compile against MbedTLS 3.0
        run: |
          sudo rm $(cat mbedtls/build/install_manifest.txt)
          git -C mbedtls fetch --depth=1 origin tag v3.0.0
          git -C mbedtls checkout v3.0.0
          ninja -C mbedtls/build
          sudo ninja -C mbedtls/build install
          ninja -C build

  build-alpine:
    runs-on: ${{ github.repository_owner == 'SiliconLabsInternal' && 'silabs-internal' || 'ubuntu-24.04' }}
    container:
      image: ${{ github.repository_owner == 'SiliconLabsInternal' && 'artifactory.silabs.net/wisun-docker-proxy/' || '' }}i386/alpine:latest
    steps:
      - name: Install dependencies
        run: |
          apk add musl-dev bsd-compat-headers gcc g++ cmake samurai \
                  mbedtls-dev mbedtls-static libnl3-dev libcap-dev git
      - name: Checkout
        run: |
          git clone --depth=1 \
                    --revision=${{ github.sha }} \
                    https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} \
                    "$GITHUB_WORKSPACE"
      - name: Compile on 32bit Alpine
        run: |
          cmake -S . \
                -B build \
                -D COMPILE_WSRD=ON \
                -D COMPILE_DEVTOOLS=ON \
                -D COMPILE_DEMOS=ON \
                -D CMAKE_C_FLAGS=-Werror \
                -G Ninja
          ninja -C build
